# Đề bài về nhà

## Yêu cầu

- Tự viết code cho mô hình Linear Regression theo công thức đã được dạy trong buổi lý thuyết trên lớp.
- Tự viết hàm dự đoán.
- Huấn luyện cả mô hình của thư viện và mô hình mình tự viết.
- In ra các trọng số: w0, w1, w2, ..., wn của cả 2 mô hình đã huấn luyện để quan sát và so sánh.
- Dự đoán dữ liệu tập test bằng cả 2 mô hình (mô hình thư viện thì dùng hàm predict() của thư viện, mô hình tự viết dùng hàm dự đoán tự viết), in ra kết quả bằng Dataframe như trong bài thực hành trên lớp.
- Tính RMSE trên tập test cho cả 2 mô hình và so sánh.

## Dữ liệu

Tập dữ liệu giá nhà ở Boston đã có sẵn trên sklearn, dữ liệu đã được chuẩn hóa và chia thành tập train, tập test

In [150]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd 
import math 

from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

# Đọc dữ liệu 

Dữ liệu về giá nhà ở Boston được hỗ trợ bởi sklearn, đọc dữ liệu thông qua hàm `datasets.load_boston()` 

Xem thêm các bộ dữ liệu khác tại https://scikit-learn.org/stable/datasets/index.html#toy-datasets. 

Dữ liệu được chia thành các thành phần data và target như tập diabetes. Dữ liệu cũng đã được chuẩn hóa, chỉ cần gọi ra và huấn luyện

In [151]:
# lay du lieu dataset - du lieu ve giá nhà
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv("BostonHousing.csv")    
df.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

**Chia dữ liệu làm 2 phần training 404 mẫu và testing 102 mẫu**

In [202]:
# cat nho du lieu, lay 1 phan cho qua trinh thu nghiem,
# chia train test cac mau du lieu
X=df.drop(['medv'],axis=1)
Y=df['medv']
X=(X-X.mean())/(X.max()-X.min())
X.shape
train_size=0.8
x_train = X[:(int)(len(X)*train_size)]
y_train = Y[:(int)(len(X)*train_size)]
x_test = X[(int)(len(X)*train_size):]
y_test = Y[(int)(len(X)*train_size):]
x_train.info()
print(f"Số lượng train và test là : {len(x_train)} và {len(x_test)}")

<class 'pandas.DataFrame'>
RangeIndex: 404 entries, 0 to 403
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   crim     404 non-null    float64
 1   zn       404 non-null    float64
 2   indus    404 non-null    float64
 3   chas     404 non-null    float64
 4   nox      404 non-null    float64
 5   rm       404 non-null    float64
 6   age      404 non-null    float64
 7   dis      404 non-null    float64
 8   rad      404 non-null    float64
 9   tax      404 non-null    float64
 10  ptratio  404 non-null    float64
 11  b        404 non-null    float64
 12  lstat    404 non-null    float64
dtypes: float64(13)
memory usage: 41.2 KB
Số lượng train và test là : 404 và 102

# 3.Xây dựng mô hình

## 3.1.Xây dựng mô hình bằng thư viện

In [203]:
from sklearn import linear_model
reg = linear_model.LinearRegression()

## 3.2.Xây dựng mô hình Linear Regression tự viết

In [204]:

one_col=np.ones((len(x_train),1))
A=np.concatenate((one_col,x_train),axis=1)#Tạo ma trận A m*(n+1)
print(A[:5])

A_T=np.transpose(A)#Ma trận chuyển vị A
w=np.dot(A_T,A)
w=np.linalg.inv(w)#Ma trận nghịch đảo
w=np.dot(w,np.dot(A_T,y_train))
w.shape

[[ 1.         -0.0405441   0.06636364 -0.32356227 -0.06916996 -0.03435197
   0.05563625 -0.03475696  0.02682186 -0.37171335 -0.21419304 -0.33569506
   0.10143217 -0.21172912]
 [ 1.         -0.04030818 -0.11363636 -0.14907546 -0.06916996 -0.17632728
   0.02612869  0.10633469  0.1065807  -0.32823509 -0.31724648 -0.06973762
   0.10143217 -0.09693883]
 [ 1.         -0.0403084  -0.11363636 -0.14907546 -0.06916996 -0.17632728
   0.17251688 -0.07698147  0.1065807  -0.32823509 -0.31724648 -0.06973762
   0.09116942 -0.23794325]
 [ 1.         -0.0402513  -0.11363636 -0.32832766 -0.06916996 -0.19896103
   0.13668626 -0.23455099  0.20616331 -0.28475683 -0.35541442  0.02600706
   0.09570823 -0.26802051]
 [ 1.         -0.03983903 -0.11363636 -0.32832766 -0.06916996 -0.19896103
   0.16523579 -0.14804224  0.20616331 -0.28475683 -0.35541442  0.02600706
   0.10143217 -0.20207128]]

(14,)

## 3.3.Hàm test mô hình tự viết

In [205]:
def predict_model(w,x_test):
    bias=w[0]
    coef=w[1:]
    coef=coef.reshape(len(coef),1)
    y_pred=np.dot(x_test,coef)+bias
    return y_pred

# 4.Huấn luyện mô hình

## 4.1.Huấn luyện mô hình của thư viện

In [206]:
model=reg.fit(x_train,y_train)
print(model.get_params())

{'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'positive': False, 'tol': 1e-06}

## 4.2.Training mô hình bằng Linear regression tự viết

In [207]:
y_pred=predict_model(w,x_test)
y_pred=y_pred.reshape(-1)
y_pred.shape

(102,)

# 5.Dự đoán các mẫu dữ liệu

## 5.1.Dự đoán các mẫu dữ liệu theo mô hình của thư viện

In [208]:
y_pred1=model.predict(x_test)
pd.DataFrame(data=np.array([y_test, y_pred1,abs(y_test - y_pred1),abs(y_test-y_pred1)*100/y_test]).T,columns=["Thực tế", "Dự đoán", "Lệch","Lệch theo %"])

     Thực tế    Dự đoán       Lệch  Lệch theo %
0        8.5   5.886799   2.613201    30.743538
1        5.0   3.787057   1.212943    24.258861
2       11.9   6.640550   5.259450    44.197061
3       27.9  21.312765   6.587235    23.610161
4       17.2  15.412714   1.787286    10.391197
..       ...        ...        ...          ...
97      22.4  23.755044   1.355044     6.049305
98      20.6  22.081673   1.481673     7.192586
99      23.9  28.181773   4.281773    17.915366
100     22.0  26.572420   4.572420    20.783729
101     11.9  22.020566  10.120566    85.046777

[102 rows x 4 columns]

## 5.2.Dự đoán các mẫu dữ liệu tính theo linear regression tự viết

In [209]:
pd.DataFrame(data=np.array([y_test, y_pred,abs(y_test - y_pred),abs(y_test-y_pred)*100/y_test]).T,columns=["Thực tế", "Dự đoán", "Lệch","Lệch theo %"])

     Thực tế    Dự đoán       Lệch  Lệch theo %
0        8.5   5.886799   2.613201    30.743538
1        5.0   3.787057   1.212943    24.258861
2       11.9   6.640550   5.259450    44.197061
3       27.9  21.312765   6.587235    23.610161
4       17.2  15.412714   1.787286    10.391197
..       ...        ...        ...          ...
97      22.4  23.755044   1.355044     6.049305
98      20.6  22.081673   1.481673     7.192586
99      23.9  28.181773   4.281773    17.915366
100     22.0  26.572420   4.572420    20.783729
101     11.9  22.020566  10.120566    85.046777

[102 rows x 4 columns]

## 5.3.Đánh giá mô hình linear regression của thư viện

In [210]:
print('RMSE:', np.sqrt(mean_squared_error(y_test, y_pred1)))
print('R2 Score:', r2_score(y_test, y_pred1))

RMSE: 5.727116436760025
R2 Score: -0.21985315040423026

## 5.4.Đánh giá mô hình linear regression tự viết

In [211]:

print('RMSE:', np.sqrt(mean_squared_error(y_test, y_pred)))
print('R2 Score:', r2_score(y_test, y_pred))

RMSE: 5.727116436760179
R2 Score: -0.21985315040429554